AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
Metrics/BlockLength:
  Exclude:
  - '**/spec/**/*.rb'
Style/Documentation:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
